// 学校校徽映射：素材来自 github.com/soulteary/china-university-icon（CC0-1.0）
// SVG 文件在 public/school-logos/，新增学校只需放文件并在此加一行
const SCHOOL_LOGO_CODES: Record<string, string> = {
  "上海中医药大学": "SHUTCM",
  "上海交通大学": "SJTU",
  "上海外国语大学": "SISU",
  "上海海洋大学": "SHOU",
  "上海科技大学": "SHANGHAITECH",
  "上海财经大学": "SUFE",
  "上海音乐学院": "SHCM",
  "东北大学": "NEU",
  "东北师范大学": "NENU",
  "东华大学": "DHU",
  "东南大学": "SEU",
  "中南大学": "CSU",
  "中国人民大学": "RUC",
  "中国传媒大学": "CUC",
  "中国农业大学": "CAU",
  "中国政法大学": "CUPL",
  "中国海洋大学": "OUC",
  "中国石油大学（北京）": "CUP",
  "中国石油大学（华东）": "UPC",
  "中国科学技术大学": "USTC",
  "中国科学院": "CAS",
  "中国科学院大学": "CAS",
  "中国美术学院": "CAA",
  "中央戏剧学院": "THE-CENTRAL-ACADEMY-OF-DRAMA",
  "中央民族大学": "MUC",
  "中央美术学院": "CAFA",
  "中央音乐学院": "CCOM",
  "中山大学": "SYSU",
  "中科院": "CAS",
  "云南大学": "YNU",
  "兰州大学": "LZU",
  "北京中医药大学": "BUCM",
  "北京交通大学": "BJTU",
  "北京体育大学": "BSU",
  "北京化工大学": "BUCT",
  "北京外国语大学": "BFSU",
  "北京大学": "PKU",
  "北京师范大学": "BNU",
  "北京理工大学": "BIT",
  "北京科技大学": "USTB",
  "北京航空航天大学": "BUAA",
  "北京邮电大学": "BUPT",
  "北大": "PKU",
  "华东师范大学": "ECNU",
  "华东理工大学": "ECUST",
  "华中农业大学": "HZAU",
  "华中科技大学": "HUST",
  "华北电力大学": "NCEPU",
  "华南师范大学": "SCNU",
  "华南理工大学": "SCUT",
  "南京中医药大学": "NJUCM",
  "南京信息工程大学": "NUIST",
  "南京大学": "NJU",
  "南京师范大学": "NJNU",
  "南京理工大学": "NJUST",
  "南京邮电大学": "NJUPT",
  "南开": "NKU",
  "南开大学": "NKU",
  "南方科技大学": "SUSTECH",
  "厦门大学": "XMU",
  "合肥学院": "HFUU",
  "吉林大学": "JLU",
  "同济大学": "TJU",
  "哈尔滨工业大学": "HIT",
  "哈尔滨工程大学": "HEU",
  "四川农业大学": "SICAU",
  "四川大学": "SCU",
  "国科大": "CAS",
  "国防科学技术大学": "NUDT",
  "复旦大学": "FDU",
  "大连理工大学": "DUT",
  "天津工业大学": "TGU",
  "宁波大学": "NBU",
  "宁波诺丁汉大学": "UNNC",
  "山东大学": "SDU",
  "广州中医药大学": "GZUCM",
  "广西大学": "GXU",
  "延边大学": "YBU",
  "成都理工大学": "CDUT",
  "新疆大学": "XJU",
  "暨南大学": "JNU",
  "武汉大学": "WHU",
  "武汉科技大学": "WUST",
  "江西师范大学": "JXNU",
  "河南工业大学": "HAUT",
  "河南工程学院": "HAUE",
  "河海大学": "HHU",
  "洛阳理工学院": "LIT",
  "浙江大学": "ZJU",
  "深圳大学": "SZU",
  "清华": "THU",
  "清华大学": "THU",
  "湖北中医药大学": "HBUCM",
  "湖南大学": "HNU",
  "湖南师范大学": "HNNU",
  "电子科技大学": "UESTC",
  "福州大学": "FZU",
  "福建工程学院": "FJUT",
  "苏州大学": "SUDA",
  "西北大学": "NWU",
  "西北工业大学": "NWPU",
  "西南交通大学": "SWJTU",
  "西南民族大学": "SWUN",
  "西南财经大学": "SWUFE",
  "西安交通大学": "XJTU",
  "西安电子科技大学": "XDU",
  "西湖大学": "WU",
  "西藏大学": "UTIBET",
  "贵州大学": "GZU",
  "贵州师范大学": "GZNU",
  "郑州大学": "ZZU",
  "重庆大学": "CQU",
  "长安大学": "CHU",
  "陕西师范大学": "SNNU",
  "青岛理工大学": "QUT",
  "青海大学": "QHU",
  "首都师范大学": "CNU",
  "香港中文大学": "CUHK",
};

const BASE = import.meta.env.BASE_URL;

// 常见中文 ↔ 英文/缩写别名（命中其一即取该 code）。
// 维护时把同一所学校的中文名、英文名、缩写都映射到同一个 code。
const ALIASES: Record<string, string> = {
  "Nanjing University": "NJU", "NJU": "NJU",
  "Tsinghua University": "THU", "Tsinghua": "THU",
  "Peking University": "PKU", "PKU": "PKU",
  "Fudan University": "FDU", "Fudan": "FDU",
  "Shanghai Jiao Tong University": "SJTU", "SJTU": "SJTU",
  "Zhejiang University": "ZJU", "ZJU": "ZJU",
  "University of Science and Technology of China": "USTC", "USTC": "USTC",
  "Tongji University": "TJU", "Tongji": "TJU",
  "Wuhan University": "WHU", "WHU": "WHU",
  "Huazhong University of Science and Technology": "HUST", "HUST": "HUST",
  "Sun Yat-sen University": "SYSU", "SYSU": "SYSU",
  "Sichuan University": "SCU", "SCU": "SCU",
  "Shandong University": "SDU", "SDU": "SDU",
  "Nankai University": "NKU", "NKU": "NKU",
  "Xiamen University": "XMU", "XMU": "XMU",
  "Jilin University": "JLU", "JLU": "JLU",
  "Renmin University of China": "RUC", "RUC": "RUC",
  "Beijing Institute of Technology": "BIT", "BIT": "BIT",
  "Beihang University": "BUAA", "BUAA": "BUAA",
  "Beijing University of Posts and Telecommunications": "BUPT", "BUPT": "BUPT",
  "University of Chinese Academy of Sciences": "CAS", "UCAS": "CAS",
  "Chinese University of Hong Kong": "CUHK", "CUHK": "CUHK",
  "Hong Kong University of Science and Technology": "HKUST", "HKUST": "HKUST",
  "The Chinese University of Hong Kong, Shenzhen": "CUHK", "CUHK-Shenzhen": "CUHK",
  "National University of Defense Technology": "NUDT", "NUDT": "NUDT",
  "University of Electronic Science and Technology of China": "UESTC", "UESTC": "UESTC",
  "Harbin Institute of Technology": "HIT", "HIT": "HIT",
  "South China University of Technology": "SCUT", "SCUT": "SCUT",
  "Dalian University of Technology": "DUT", "DUT": "DUT",
  "Central South University": "CSU", "CSU": "CSU",
  "Northwestern Polytechnical University": "NWPU", "NWPU": "NWPU",
  "Xi'an Jiaotong University": "XJTU", "XJTU": "XJTU",
  "Southeast University": "SEU", "SEU": "SEU",
  "Chongqing University": "CQU", "CQU": "CQU",
  "Lanzhou University": "LZU", "LZU": "LZU",
  "Ocean University of China": "OUC", "OUC": "OUC",
  "Hunan University": "HNU", "HNU": "HNU",
  "East China Normal University": "ECNU", "ECNU": "ECNU",
  "Beijing Normal University": "BNU", "BNU": "BNU",
  "Nanjing University of Aeronautics and Astronautics": "NUAA", "NUAA": "NUAA",
};

/** 按机构名找校徽 URL：精确 → 英文别名 → 中文核心包含三级匹配 */
export function getSchoolLogo(org: string): string | null {
  const name = (org || "").trim();
  if (!name) return null;
  // 1. 中文精确命中
  const direct = SCHOOL_LOGO_CODES[name];
  if (direct) return `${BASE}school-logos/${direct}.svg`;
  // 2. 英文/缩写别名（整名或忽略大小写精确命中）
  const alias = ALIASES[name] || ALIASES[name.toLowerCase()];
  if (alias) return `${BASE}school-logos/${alias}.svg`;
  // 3. 英文别名包含匹配（如 "Nanjing University of Aeronautics..." 含 Nanjing University）
  const lname = name.toLowerCase();
  for (const [key, code] of Object.entries(ALIASES)) {
    if (key.length >= 4 && (lname.includes(key.toLowerCase()) || key.toLowerCase().includes(lname))) {
      return `${BASE}school-logos/${code}.svg`;
    }
  }
  // 4. 中文核心包含匹配（如"南开大学计算机学院"命中"南开大学"）
  for (const [school, code] of Object.entries(SCHOOL_LOGO_CODES)) {
    if (school.length >= 2 && (name.includes(school) || school.includes(name))) {
      return `${BASE}school-logos/${code}.svg`;
    }
  }
  return null;
}
