"""人工核对的师生图谱别名。只合并已确认指向同一实体的写法。"""

SCHOOL_ALIASES = {
    "Hong Kong Polytechnic University": "香港理工大学",
    "The Hong Kong Polytechnic University": "香港理工大学",
    "Huazhong University of Science and Technology": "华中科技大学",
    "The Chinese University of Hong Kong": "香港中文大学",
    "The Chinese University of Hong Kong, Shenzhen": "香港中文大学（深圳）",
    "The University of Hong Kong": "香港大学",
    "香港大学 The University of Hong Kong": "香港大学",
    "香港大学（The University of Hong Kong）": "香港大学",
    "The University of Sydney": "悉尼大学",
    "Tsinghua University": "清华大学",
    "Zhejiang University": "浙江大学",
    "中国人民大学 Renmin University of China": "中国人民大学",
    "复旦": "复旦大学",
    "上海创智学院/复旦大学": "复旦大学 / 上海创智学院",
    "复旦大学 / 上海创智学院（国家人工智能学院）": "复旦大学 / 上海创智学院",
    "浙江大学计算机科学与技术学院": "浙江大学",
    "北京大学前沿交叉学科研究院": "北京大学",
}

# 每条别名均来自现有导师记录的姓名、单位或中英文对照，未确认的同名者保留独立。
ADVISOR_ALIASES = {
    "Chua Tat-Seng": "Tat-Seng Chua",
    "Liao Lizi": "Lizi Liao",
    "Hanwang Zhang": "Zhang Hanwang",
    "LI Qing": "李青",
    "李青（Qing Li，香港理工大学）": "李青",
    "Fan Wenqi": "范文琦",
    "范文琦（Wenqi Fan，港理工）": "范文琦",
    "Fuli Feng": "冯福利",
    "Liu Ziwei": "刘子纬",
    "刘子纬 Liu Ziwei": "刘子纬",
    "Yuanwei Liu": "刘元玮",
    "刘元玮 Yuanwei Liu": "刘元玮",
    "刘元玮（Yuanwei Liu，港大）": "刘元玮",
    "Tongliang Liu": "刘同亮",
    "Chunhua Shen": "沈春华",
    "丁辉（首都师范大学，dhui@cnu.edu.cn）": "丁辉",
    "东昱晓（清华大学）": "东昱晓",
    "严骏驰（上海交通大学，yanjunchi@sjtu.edu.cn）": "严骏驰",
    "于红波（清华大学，yuhongbo@mail.tsinghua.edu.cn）": "于红波 Hongbo Yu",
    "仉尚航（北京大学）": "仉尚航",
    "付章杰（南京信息工程大学，fzj@nuist.edu.cn）": "付章杰",
    "任炬（清华大学）": "任炬",
    "伍楷舜（港科大广州）": "伍楷舜",
    "刘勇攀（Yongpan Liu，清华大学）": "刘勇攀",
    "刘华平（清华大学）": "刘华平",
    "刘奕群（清华大学，yiqunliu@tsinghua.edu.cn）": "刘奕群",
    "司鑫（东南大学集成电路学院）": "司鑫",
    "吴晔（北师大）": "吴晔",
    "周晓禹（北师大，合作导师）": "周晓禹（北京师范大学）",
    "周煊赫（上海交通大学）": "周煊赫",
    "喻纯（清华大学）": "喻纯",
    "孙广宇（北大集成电路学院）": "孙广宇",
    "孙栩（北京大学）": "孙栩",
    "孟高峰（中科院自动化所，外部导师）": "孟高峰",
    "孟高峰（中科院自动化所）": "孟高峰",
    "安竹林（中科院计算所）": "安竹林",
    "宋明黎（浙江大学）": "宋明黎",
    "尉寅玮（山东大学）": "尉寅玮",
    "崔斌（北京大学）": "崔斌",
    "应明生（清华大学）": "应明生",
    "康嘉文（广东工业大学）": "康嘉文",
    "张宁（Ning Zhang，温莎大学）": "张宁",
    "张宁豫（浙江大学，zhangningyu@zju.edu.cn）": "张宁豫",
    "张宸（上海交通大学）": "张宸",
    "张小平（清华大学）": "张小平",
    "张岳（西湖大学，zhangyue@westlake.edu.cn）": "张岳",
    "张敏（清华大学，z-m@tsinghua.edu.cn）": "张敏",
    "徐君（中国人民大学，junxu1@foxmail.com）": "徐君",
    "慈玉生（哈尔滨工业大学，15904606182@126.com）": "慈玉生",
    "操晓春（中山大学）": "操晓春",
    "曹艺馨（复旦大学）": "曹艺馨",
    "曹艺馨（复旦大学/上海创智学院）": "曹艺馨",
    "朱军（清华大学）": "朱军",
    "朱磊（同济大学，leizhu0608@gmail.com）": "朱磊",
    "李建欣（北京航空航天大学）": "李建欣",
    "李文斌（南京大学）": "李文斌",
    "李昊昂（香港科技大学广州，haoangli@hkust-gz.edu.cn）": "李昊昂",
    "李素建（北京大学，lisujian@pku.edu.cn）": "李素建",
    "杨智勇（中国科学院大学，yangzhiyong21@ucas.ac.cn）": "杨智勇",
    "林宙辰（北京大学，zlin@pku.edu.cn）": "林宙辰",
    "桂杰（东南大学）": "桂杰",
    "汪云海（中国人民大学）": "汪云海",
    "汪军 Jun Wang": "汪军",
    "汪军（Jun Wang，UCL）": "汪军",
    "汪玉（清华大学）": "汪玉",
    "洪日昌（Richard Hong）": "洪日昌",
    "潘世瑞（Shirui Pan）": "潘世瑞",
    "潘旭东（复旦大学）": "潘旭东",
    "潘玲（Ling Pan，香港科技大学，lingpan@ust.hk）": "潘玲",
    "熊欢（哈尔滨工业大学）": "熊欢",
    "王宏宁（清华大学，wang.hongn@gmail.com）": "王宏宁",
    "王志春（北京师范大学）": "王志春",
    "王杰新（华南理工大学）": "王杰新",
    "王树徽（中科院计算所）": "王树徽",
    "王翔（中国科学技术大学）": "王翔",
    "王贺升（上海交大）": "王贺升",
    "王钰（上海交通大学）": "王钰",
    "王钺（清华大学，wangyue@mail.tsinghua.edu.cn）": "王钺",
    "程建（电子科技大学）": "程建",
    "罗平 Luo Ping": "罗平",
    "罗平（西湖大学，pluo.lhi@gmail.com）": "罗平",
    "胡文波（合肥工业大学）": "胡文波",
    "聂礼强（山东大学）": "聂礼强",
    "苏权科（港科大广州，quankesu@hkust-gz.edu.cn）": "苏权科",
    "范举 Ju Fan": "范举",
    "范举（中国人民大学，fanj@ruc.edu.cn）": "范举",
    "范举（中国人民大学）": "范举",
    "薛巍（清华大学）": "薛巍",
    "裴剑锋（北京大学，jfpei@pku.edu.cn）": "裴剑锋",
    "许倩倩（中科院计算所）": "许倩倩",
    "许斌（清华大学）": "许斌",
    "许杰（Xu Jie）": "许杰",
    "赵俊峰（北京大学）": "赵俊峰",
    "邹逸雄（华中科技大学，yixiongz@hust.edu.cn）": "邹逸雄",
    "郝建业（天津大学，yuanyf@tju.edu.cn）": "郝建业",
    "郭嘉丰（中科院计算所）": "郭嘉丰",
    "金琴（中国人民大学）": "金琴",
    "钱彦旻（上海交通大学）": "钱彦旻",
    "乔宇（中科院深圳理工/SIAT）": "乔宇",
    "陈为（浙江大学，chenvis@zju.edu.cn）": "陈为",
    "陈挺（清华大学）": "陈挺",
    "陶大程（Dacheng Tao，NTU）": "陶大程",
    "陶大程（Dacheng Tao）": "陶大程",
    "饶安逸（RAO Anyi，香港科技大学）": "饶安逸",
    "高飞飞（清华大学）": "高飞飞",
    "黄民烈（清华大学，aihuang@tsinghua.edu.cn）": "黄民烈",
    "黄超（Chao Huang，chaohuang75@gmail.com）": "黄超",
    "黄超（Chao Huang）": "黄超",
}


def canonical_school(name: str) -> str:
    return SCHOOL_ALIASES.get((name or "").strip(), (name or "").strip())


def canonical_advisor(name: str) -> str:
    return ADVISOR_ALIASES.get((name or "").strip(), (name or "").strip())
